### ISSUE TITLE
webpack is really really slow and sometimes crashes with OOM

### ISSUE THREAD

**Issue by fxck** [AngularClass/angular2-webpack-starter#372]
I haven't really messed with any of the configs, yet after adding a couple of components the build times are getting incredibly long(around 40 sec is no exception), that is on the first run of `npm run server`, after a while(few changes in files, watch triggered couple of times), it will get stuck on  `90% optimize assets` and then crash with the error below. 

I'm really not sure how to debug this, and I'm not aware of doing something hacky in my code(there are no typescript errors at very least, and I'm not aware of any cycle dependency either) that could possibly cause it to go mental like this. 

How should I proceed? Are there any common mistakes that would cause this, and I should look for? Would it help if I posted my repo? :|

I'm running the latest version of angular2-webpack-starter and node 5.7.0
 

```
 90% optimize assets
<--- Last few GCs --->

  282958 ms: Mark-sweep 1378.9 (1456.7) -> 1381.9 (1456.7) MB, 2960.5 / 0 ms [allocation failure] [GC in old space requested].
  285856 ms: Mark-sweep 1381.9 (1456.7) -> 1381.9 (1456.7) MB, 2898.3 / 0 ms [allocation failure] [GC in old space requested].
  288814 ms: Mark-sweep 1381.9 (1456.7) -> 1377.1 (1456.7) MB, 2957.6 / 0 ms [last resort gc].
  291789 ms: Mark-sweep 1377.1 (1456.7) -> 1378.6 (1456.7) MB, 2975.3 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xff19f0e3ac1 <JS Object>
    1: copyMap [/srv/bubble/users/ar/ng2-base/repo/node_modules/typescript/lib/typescript.js:1198] [pc=0x3b78ca2abb95] (this=0x36735faa3a1 <an Object with map 0x1c3192bf1da1>,source=0x1a165d296929 <an Object with map 0x1c3192bbc3a1>,target=0x9118a8a3ef1 <an Object with map 0x2b40e4710441>)
    2: objectTypeRelatedTo(aka objectTypeRelatedTo) [/srv/bubble/users/ar/ng2-base/repo/node_modules/typesc...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted
```

**Comment by jkyoutsey** [comment]
I've seen this error over and over again as well.
I've had it fail on module build steps as well as optimize assets.

**Comment by alvipeo** [comment]
I upgraded my package.json this morning and got the same errors. So I'm going to roll back where it was. Something is clearly broken. And it's not typescript, I checked.

**Comment by jkyoutsey** [comment]
I've managed to get my dev build working, but npm run build:prod fails at the same point every time.
I've tried upping the memory limit on node to no avail.
`node --max_old_space_size=8092 ./node_modules/webpack/bin/webpack.js`

**Comment by fxck** [comment]
@alvipeo I tried it at different points of time, not with just the latest version, and it always incrementally slows down(build times that is), and eventually starts crashing... Basically fresh webpack starter takes about 5 seconds to build, 10 component and couple of services later (all in all somewhere about 300 LOC in total), it takes 40 seconds and is crashing. It's impossible to develop like this..

**Comment by alvipeo** [comment]
I completely agree with you. I've been a Microsoft tools user for a long time so I used to higher level quality dev tools. But had to switch to this "modern" build tools 6 months ago and it sucks. From configuration to the actual usage. Except for VS Code which is really fast!

Having said all that, we have no choice for now I guess :( There's also rollupjs and babel. But I have no will and time to spend that much time on this...

**Comment by alvipeo** [comment]
I'm curious, are you guys on Windows or Mac?

**Comment by jkyoutsey** [comment]
I am on Mac.

**Comment by alvipeo** [comment]
ok, I thought maybe it's just Windows. It's not..

**Comment by jkyoutsey** [comment]
Okay, I've eliminated this error in my prod builds by commenting out the
`new ProvidePlugin({...})`
in the webpack.prod.config.

**Comment by alvipeo** [comment]
Did not work for me.

**Comment by jkyoutsey** [comment]
@alvipeo Not surprised.  For as often as my dev build fails on hot recompiles I was surprised I got anything to work.

**Comment by fxck** [comment]
@gdi2290 any chance you'd look into this, please? At least tell us whether this could possibly have something to do with how angular-webpack-starter is set up, or it's rather a webpack/typescript problem and we should fill issues in their respective repos..

**Comment by sumigoma** [comment]
+1 Also seeing this.

**Comment by fxck** [comment]
I find it really moody, sometimes it works flawlessly, I comment out one innocent line of code and it crashes...

**Comment by gdi2290** [comment]
the CompressionPlugin and ProvidePlugin plugins might be eating up a lot of memory

**Comment by fxck** [comment]
Those are not in dev server, are they? And it crashes in dev as well..

**Comment by alvipeo** [comment]
Don't have them either and the build crashes... :(

**Comment by gdi2290** [comment]
it might be webpackMerge and the default config I introduced

**Comment by alvipeo** [comment]
Can we roll back a bit?

**Comment by gdi2290** [comment]
can you try it now?
https://github.com/AngularClass/angular2-webpack-starter/commit/fe37a03b6e86fa7ceeb9c76e0cc59db3eb2b8d83

**Comment by gdi2290** [comment]
I'm excluding node_modules now

**Comment by alvipeo** [comment]
Let's see...

**Comment by gdi2290** [comment]
the source-map-loader adds about 2 seconds for me

**Comment by alvipeo** [comment]
I have slightly different set of packages but here's what I get for 'npm run test':

```
START:
ts-loader: Using typescript@1.8.7 and d:\Documents\Visual Studio 2015\Projects\UniGalleryCode\tsconfig.json

<--- Last few GCs --->

   61727 ms: Mark-sweep 1376.9 (1457.0) -> 1376.8 (1457.0) MB, 857.7 / 0 ms [allocation failure] [GC in old space requested].
   62585 ms: Mark-sweep 1376.8 (1457.0) -> 1376.8 (1457.0) MB, 857.7 / 0 ms [allocation failure] [GC in old space requested].
   63458 ms: Mark-sweep 1376.8 (1457.0) -> 1375.6 (1457.0) MB, 872.6 / 0 ms [last resort gc].
   64318 ms: Mark-sweep 1375.6 (1457.0) -> 1376.2 (1457.0) MB, 860.6 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000000E915AE3AD1 <JS Object>
    2: objectTypeRelatedTo(aka objectTypeRelatedTo) [d:\Documents\Visual Studio 2015\Projects\UniGalleryCode\node_modules\typescript\lib\typescript.js:19809] [pc=000001114C0F1A96] (this=000000E915A04189 <undefined>,source=0000023E3567AB41 <a TypeObject with map 000003A65E1362F9>,originalSource=0000023E3567AB41 <a TypeObject with map 000003A65E1362F9>,target=0000023E3567AC21 <a TypeObject with...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@2.0.0 test: `karma start`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@2.0.0 test script 'karma start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.
```

**Comment by gdi2290** [comment]
Thanks I'll look more into it in the morning

**Comment by alvipeo** [comment]
Do you want my project as a sample? I may give you private link. Just need your email or something...

**Comment by fxck** [comment]
Didn't help at all.. also I'm getting `Loading.. <% if (webpackConfig.metadata.ENV === 'development') { %> <% } %>` with the latest package.json and webpack.config.. like it's not parsing it correctly.

**Comment by gdi2290** [comment]
@alvipeo  ya can you email me patrick (at) gdi2290 com

**Comment by alvipeo** [comment]
Sent.

**Comment by gdi2290** [comment]
thanks, I can look at it tonight

**Comment by scatcher** [comment]
I had the same issue a few weeks ago when I was running TypesScript 1.8 beta in my build and after many long days I found that dropping back down to 1.7 resolved the OOM issue.  I just confirmed that the issue still exists in 1.8 stable in my project and that moving back down to 1.7.5 resolved the issue once again.

Hope this helps!

**Comment by hollanderbart** [comment]
rolling back to TypeScript 1.7.5 doesn't fix this for me.

**Comment by fxck** [comment]
Yep, not for me either.

**Comment by alvipeo** [comment]
I tried rolling back to 1.7.5 but that didn't help me either.

**Comment by gdi2290** [comment]
Thanks for the issue. Can update to latest and reopen if you still have this issue. The problem was ts-loader so I switched to awesome-typescript-loader so I'm closing this now

**Comment by fxck** [comment]
yes, it's noticeably faster, although it seems to ignore custom-typings

```
[default] /srv/bubble/users/ar/finalysio/repo/application/src/main.ts (145,12):
    Property 'hot' does not exist on type 'NodeModule'.

```

**Comment by fxck** [comment]
nevermind, my fault

**Comment by alvipeo** [comment]
@gdi2290 Thank you for the fix! Project works after latest changes!

**Comment by JesusisFreedom** [comment]
I'm still getting this with node 5.7.1 ts 1.8.2 and awesome-ts-loader. Was there anything else?

**Comment by alvipeo** [comment]
The only thing that doesn't really work is watch:test - it stops after 2-3 recompilations. But I almost get used to it.

**Comment by alvipeo** [comment]
Oh, I had an error with 'run test' before I upgraded to Node 5.8.0. That fixed it.

**Comment by gdi2290** [comment]
@JesusisFreedom run `npm cache clean` `rm -rf node_modules typings` `npm install` `typings install`

**Comment by kampdomoj** [comment]
Still having the same issue after upgrading to the latest version
npm cache clean etc didn't help

**Comment by broth-eu** [comment]
I'm also having this issue. Is there any solution or workaround?

**Comment by hollanderbart** [comment]
Yes, temporary solution https://github.com/AngularClass/angular2-webpack-starter/pull/449, just download the latest version.
You can also try to work with the latest Rxjs version (5.0.0-beta.3).

**Comment by broth-eu** [comment]
With increasing the memory it works, thanks. Unfortunately, it's extremely slow now.

How can I use the latest Rxjs version? When I try to update I always get the error "UNMET PER DEPENDENCY rxjs@5.0.0-beta.3" since the latest Angular2 version requires Rxjs 5.0.0-beta.2.

**Comment by hollanderbart** [comment]
I will try it now. Please run npm install for the second time.

**Comment by gdi2290** [comment]
@broth-eu there's a problem with beta.3 in rx so they will release beta.4 soon

**Comment by broth-eu** [comment]
@hollanderbart running npm install twice works, thanks
@gdi2290 nevertheless, Rxjs beta.3 seems to work. Only IntelliJ shows me some errors with the Observable interface due to the ambient method declarations.

**Comment by alvipeo** [comment]
With RxJS beta.3 I got this - https://github.com/ReactiveX/rxjs/issues/1507.

**Comment by zigzag95** [comment]
Please reopen this.
OOM at 92% Optimizing assets
