### ISSUE TITLE
End-to-end tests failure

### ISSUE THREAD

**Issue by Redigast13** [AngularClass/angular2-webpack-starter#1353]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
I have errors if I run e2e tests:
In first terminal:
npm run webdriver:update
npm run webdriver:start
In second terminal:
npm run e2e

I get this error in second terminal:
E/launcher - Error: TSError: ? Unable to compile TypeScript
Conflicting definitions for 'selenium-webdriver' found at 'd:/web/angular2
-webpack-starter/node_modules/@types/selenium-webdriver/index.d.ts' and 'd:/web/angular2-webpack-starter/node_modules/protractor/node_modules/@types/selenium-webdriver/index.d.ts'. Consider installing a specific version of this library to resolve the conflict. (4090)

I also get an error if I run e2e:live tests:
npm run e2e:live

ERROR: Invalid Option: --elementExplorer

* **Please tell us about your environment:**

- Angular version: 2.4.2
- Browser: [ Chrome 55.0.2883.87 m ]

**Comment by pwoloszun** [comment]
+1

**Comment by glendaviesnz** [comment]
The latest version of Protractor has its own copy of the selenuim typings so @types/selenium is not needed, so if you do 
```
npm uninstall @types/selenium
```
it should fix the first error. Not sure about the second error sorry.

Glen

**Comment by GenZodd** [comment]
Running the uninstall command did not change anything for me. I still get the same error.

**Comment by colinskow** [comment]
Try this:

```bash
npm run clean
npm install
npm run build:prod
npm run e2e
```

`webdriver:update` and `webdriver:start` are uneccesary in the latest version of this starter. We probably need to update the docs to reflect this, and clean up deprecated scripts.

**Comment by yvChauhan** [comment]
@colinskow , still same issue i run all command provided by you, however, while running e2e i am facing same issue as mentioned by  @Redigast13

**Comment by colinskow** [comment]
This works for me fine after cloning master. What version of TypeScript are you using? (`tsc --version`) This project (and Angular) work with TypeScript 2.0.10 and are not yet compatible with TS 2.1.x.

This is unlikely to break here, as it is covered in the CI test suite.

**Comment by shlomiassaf** [comment]
With 2.4.1 and TS 2.1.4 everything works great

**Comment by colinskow** [comment]
My advice is check your versions of `@types/selenium-webdriver` and `protractor` against our `package.json` in master. You are likely using versions of something with incompatible types.

**Comment by yvChauhan** [comment]
Finally, i got this working, thanks to @glendaviesnz for pointing out fact that protractor also has selenium, which was conflicting with @type/selenium version, I changed @type/selenium version to match protractor selenium version, and e2e run flawlessly.

However while running e2e:live I am getting following error
![image](https://cloud.githubusercontent.com/assets/11193564/21878073/a21633fc-d8b5-11e6-9593-51bd7c8135c4.png)

**Comment by GenZodd** [comment]
Not sure if this is the correct/best answer but since the error was saying it did not like finding two typings in the tsconfig.json file I just removed the reference to "selenium-webdriver" and e2e started working.

**Comment by glendaviesnz** [comment]
@yvChauhan  - for some reason Windows does not like the way the --elementExplorer param is passed in. I haven't got time to work out a proper fix at the moment, but in the meantime if you edit your package.json for e2e:live script and add the e2e:debug line as below e2e:live should then work:  

    "e2e:live": "npm-run-all -p -r server:prod:ci e2e:debug",
    "e2e:debug": "protractor --elementExplorer",

Glen

**Comment by colinskow** [comment]
--elementExplorer is fixed in #1367

**Comment by colinskow** [comment]
When I tested master on Windows I ran into this issue. It is another Windows-specific issue.

The fix is to remove `selenium-webdriver` from `types` in `tsconfig.json`. I will submit this in my next PR.
